CREATE OR REPLACE TABLE restaurants (
	id VARCHAR(30) NOT NULL UNIQUE,
	name VARCHAR(30),
	address VARCHAR(50),
	lat VARCHAR(20),
	lng VARCHAR(20),
	PRIMARY KEY(id)
);
CREATE OR REPLACE TABLE tags (
	id VARCHAR(30) NOT NULL,
	tag VARCHAR(30));
